version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: gorm
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
    volumes:
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
